name: Run Tests on Ubuntu

on:
  push

jobs:

  build:

    runs-on: ubuntu-20.04

    strategy:
      matrix:
        include:
          - nginxVersion: 1.13.3-1
          - nginxVersion: 1.12.0-1
          - nginxVersion: 1.11.9-0
          - nginxVersion: 1.11.5-0
          - nginxVersion: 1.10.1-3
          - nginxVersion: 1.10.1-0

    steps:
      - uses: actions/checkout@v2
      - name: Run Tests
        env:
          NGINX_VERSION: ${{ matrix.nginxVersion }}
        run: bash run-tests.sh
